<?php

namespace App;

class CardGame
{
    protected $deckOfCards = [
        '2', '3', '4', '5', '6', '7', '8', '9', '10', 'J', 'Q', 'K', 'A'
    ];
    protected $autoSelectedCards = [];
    protected $limit = 0;


    public function setLimit($limit)
    {
        $this->limit = $limit;
    }

    /**
     * Machine generated cards
     *
     * @param Integer $limit
     *
     * @return void
     */
    public function autoGenerateCards($limit)
    {
        $this->setLimit($limit);

        for ($i = 0; $i < $this->limit; $i++) {
            $this->autoSelectedCards[] = collect($this->deckOfCards)->random();
        }
        return $this->autoSelectedCards;
    }

    public function getAutoGeneratedCards()
    {
        return $this->autoSelectedCards;
    }

    public function calculateScores($playerCards)
    {
        $player = 0;
        $generated = 0;

        for ($i = 0; $i < $this->limit; $i++) {

            // A card is tie, If both selected same card.
            // dump($playerCards[$i] . " === " . $this->autoSelectedCards[$i]);
            if ($playerCards[$i] === $this->autoSelectedCards[$i]) continue;

            if (array_search($playerCards[$i], $this->deckOfCards) > array_search($this->autoSelectedCards[$i], $this->deckOfCards)) {
                $player++;
            } else {
                $generated++;
            }
        }
        return ['player' => $player, 'generated' => $generated];
    }

    public function getDeckOfCards()
    {
        return $this->deckOfCards;
    }
}
