<?php

namespace App\Http\Controllers;

use App\CardGame;
use Illuminate\Http\Request;

class GameController extends Controller
{
    public function store(Request $request, CardGame $cardGame)
    {
        $limit = count($request->cards);











        $cardGame->autoGenerateCards($limit);

        $data['auto_generated_cards'] = $cardGame->getAutoGeneratedCards();

        $data['score'] = $cardGame->calculateScores($request->cards);

        return response($data);
    }
}
