<?php

namespace App\Http\Controllers;

use App\CardGame;
use App\Rules\ValidateCard;
use App\Score;
use App\User;
use Illuminate\Http\Request;

class GameController extends Controller
{
    public function index()
    {
        return response(Score::with('user')->orderBy('id', 'desc')->get(), 200);
    }
    public function store(Request $request, CardGame $cardGame)
    {
        $limit = count($request->cards);
        // Validation
        $this->validate(
            $request,
            [
                'full_name' => 'required|string|max:255',
                'cards' => [new ValidateCard($cardGame)]
            ]
        );

        // setting limit of auto generated cards, based on user entered cards
        $cardGame->autoGenerateCards($limit);
        //Generating cards automatically
        $data['generated_cards'] = $cardGame->getAutoGeneratedCards();
        // calculating score
        $data['score'] = $cardGame->calculateScores($request->cards);


        // Storing into database
        $user = User::create(['full_name' => $request->full_name]);

        $user->scores()->create([
            "generated_cards" => $data['generated_cards'],
            "user_cards" => $request->cards,
            "generated_points" => $data['score']['generated'],
            "user_points" => $data['score']['player'],
            "is_user_won" => $data['score']['generated'] < $data['score']['player'] ? 1 : 0,
            "is_machine_won" => $data['score']['player'] < $data['score']['generated'] ? 1 : 0,
        ]);

        return response($data);
    }
}
